// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vecbmuziaohbmleptnrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlY2JtdXppYW9oYm1sZXB0bnJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MjA1MDIsImV4cCI6MjA2ODM5NjUwMn0.7dRanGJZBEHNalh5BBLFruSiYZzNpvIeY6K50n5Yz0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});